name: Build Docker on Tag

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract tag name
        id: tag
        run: echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Build Docker image and export to tar
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          tags: myapp:${{ steps.tag.outputs.tag }}
          outputs: type=docker,dest=/tmp/elastix-${{ steps.tag.outputs.tag }}.tar

      - name: Upload Docker image as artifact
        uses: actions/upload-artifact@v4
        with:
          name:  elastix-${{ steps.tag.outputs.tag }}
          path: /tmp/elastix-${{ steps.tag.outputs.tag }}.tar
          retention-days: 30

      - name: Create GitHub Release with image
        uses: softprops/action-gh-release@v2
        with:
          files: /tmp/elastix-${{ steps.tag.outputs.tag }}.tar
          name: Release ${{ steps.tag.outputs.tag }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}

      - name: Upload Docker image to R2
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: auto
          AWS_EC2_METADATA_DISABLED: true
          R2_ENDPOINT: https://bb89f54363dfbd7fcd4f9da7a0afae51.r2.cloudflarestorage.com
          TAG: ${{ steps.tag.outputs.tag }}
        run: |
          FILE="/tmp/elastix-${TAG}.tar"
          test -f "$FILE" || { echo "::error::missing $FILE"; ls -lah /tmp; exit 1; }

          aws s3 cp "$FILE" \
            "s3://packages/elastix/elastix-${TAG}.tar" \
            --endpoint-url "$R2_ENDPOINT" \
            --metadata "tag=${TAG},commit=${GITHUB_SHA}" \
            --checksum-algorithm CRC32 \
            --no-progress